### ISSUE TITLE
Recommendation: Bget

### ISSUE THREAD

**Issue by ITCMD** [Crqshes/Baton-db#1]
Hi there Crqshes, saw your post about this on Reddit. Looks cool!

One thing I thought could make this powerful off the bat (pun inteneded), was using a tool called bget. Bget is made by a work aquantence of mine, its a database of batch codes and tools that he looks over before adding and makes sure it doesn't contain any executables. He has a great list of stuff that could be useful! Check it out here: https://github.com/jahwi/bget

There are some tools in there (such as [CMDS](https://github.com/ITCMD/cmds) which is by me) and there's also some full programs and games, I don't know if those would be helpful. I think you should be able to sort them out by category.

**Comment by Crqshes** [comment]
Heyo, Thanks for the suggestion! I'll be sure to check it out later in the afternoon after school.

**Comment by ITCMD** [comment]
Sounds great! If you want to get in contact with the creator and some like-minded folk, here's a link to the discord I work on: https://disboard.org/server/join/444186550197288970

**Comment by Crqshes** [comment]
Hi, back on the topic of Baton, from what i gather you're suggesting I should also have the option to download from bget's repository of command's?
I'm not at all opposed to this just wanting clarification.

**Comment by ITCMD** [comment]
Yeah something like that. If you look at the file that has the list of projects, there should be a way to just sort out tools if you wanted (as far as I remember), which would be more suited for this tool's use case.

**Comment by Crqshes** [comment]
Very sorry I've been quite distracted on other things recently but I'm back on track! I'm redoing it all and this feature will be added along with the feature to import from any other website or repository!
